# Lesson 07: Numpy and Pandas Modules

Very popular libraries like NumPy and Pandas are used in data science and machine learning. In this lesson, we will learn how to use these libraries in Python.

## 7.1. NumPy
- [Numpy - Official Documentation](https://numpy.org/)
- [Python Numpy Tutorial for Beginners on freeCodeCamp](https://youtu.be/QUT1VHiLmmI)

<br>

- NumPy is a library that provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
- It is very popular in data science and machine learning.
- It isn't a built-in library in Python. Therefore, we need to install it first: `pip install numpy`.
- syntax: `import numpy as np`
  - we use `as` keyword to give a name to the imported library, and we use `np` as standard name for NumPy.

### Why NumPy
> From the NumPy documentation:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

### Why is NumPy Fast?
> From the NumPy documentation:

- Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

    - vectorized code is more concise and easier to read

    - fewer lines of code generally means fewer bugs

    - the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

    - vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

- Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. 

### 7.1.1. Basic NumPy Operations

- Create NumPy Array

In [1]:
# import numpy
import numpy as np

list1 = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]

list2 = [
    [2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11]
]

list1 + list2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [2, 3, 4, 5, 6], [7, 8, 9, 10, 11]]

In [2]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
np_list1 = np.array(list1)
np_list2 = np.array(list2)
np_list1 + np_list2

array([[ 3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21]])

In [4]:
np_list1 * np_list2

array([[  2,   6,  12,  20,  30],
       [ 42,  56,  72,  90, 110]])

In [6]:
# Create np.array

np_array = np.array([[5.0, 4.0, 3.0, 2.0], [6.0, 7.0, 8.0, 9.0]])
print(np_array)

[[5. 4. 3. 2.]
 [6. 7. 8. 9.]]


In [14]:
# Creation of a NumPy Array with defined data type
np_array_type = np.array([[5.0, 4.0, 3.0, 2.0], [6.0, 7.0, 8.0, 9.0]], dtype=np.int32)  # data will be converted into int
# if the data cannot be converted into an int, it will throw an a ValueError
print(np_array_type)

[[5 4 3 2]
 [6 7 8 9]]


- Info about NumPy Array

In [9]:
# Dimension of a NumPy Array
print(np_array.ndim)

# Shape of a NumPy Array
print(np_array.shape)

2
(2, 4)


In [15]:
# Type of the elements in a NumPy Array
print(np_array.dtype)

float64
